# Site settings
title: Nacriema's Page
description: "My personal website using jekyll-template."

# baseurl: "" # for test: remove string '/space-jekyll-template' to ''
# url: "https://nacriema.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# Future post allow
future: true

# Google services
google_analytics: G-B9C4LJQ29X

# User settings
username: Nacriema
user_title: Lorem Ipsum - FrontEnd
email: huytruong2931998@gmail.com
twitter_username:
github_username: Nacriema
gplus_username:
linkedin_public_url: # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: Nacriema
profile_picture: https://github.com/Nacriema.png

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /posts/:categories/:year/:month/:day/:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: https://github.com/Nacriema
      new_tab: true
      key_trigger: g
      external: true
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: Loss Functions for Semantic Segmentation
    url: https://github.com/Nacriema/Loss-Functions-For-Semantic-Segmentation
  - name: Neural Network Interpretation
    url: https://github.com/Nacriema/Neural-Network-Interpretation
  - name: Shadow Removal Algorithm
    url: https://github.com/Nacriema/Robust_Face_Recognition

# Link to all platforms that I have to give inside the About CV section
facts:
  - name: Residence
    value: '<a href="https://www.google.com/maps/place/Qu%E1%BA%A3ng+Nam/@15.5089737,107.644709,10z/data=!4m6!3m5!1s0x31420dd4e1353a7b:0xe49cabb166747679!8m2!3d15.5393538!4d108.019102!16zL20vMDRsZl9n?entry=ttu"><i class="fa fa-home fact-icon"></i>Quangnam, Vietnam</a>'
  - name: Github
    value: '<a href="https://github.com/Nacriema"><i class="fab fa-github fact-icon"></i>Nacriema</a>'
  - name: LinkedIn
    value: '<a href="https://github.com/Nacriema"><i class="fab fa-linkedin fact-icon"></i>Nacriema</a>'
  - name: Mobile
    value: '<a href="tel:+84916694687"><i class="fa fa-phone fact-icon"></i>+84916694687</a>'


# Skills section for the About CV
skills:
  - name: XXX
    value: 100
  - name: Comedy
    value: 100
  - name: Plays
    value: 50

# Working expericences
positions:
  - company: DSoft-JSC
    location: Danang, VN
    title: AI Engineer
    period: Nov 2021 - Present
    skills: ['Python', 'Pytorch']
    contents: "[Vocably](https://vocably.pro) is a platform (extension and an app) that helps users to look up new words while surfing the web and study those words as flashcards on mobile.

              As a founder and the only developer of Vocably, I'm responsible for:

              * Developing backend with AWS / GCP / NodeJS / Lambda / API Gateway / Cognito

              * Developing frontend/mobile experience (PWA) with Angular / Amplify

              * Developing Chrome Extension with Vanilla / Web Components

              * DevOps and CI/CD with CircleCI / Terraform / NodeJS / Zx / Bash

              * Testing with Jest / Cypress / Endtest.io

              * Market analysis, product marketing, cost and pricing analysis
              "

# TODO: Define dynamic education and certifications here

# exclude my node related stuff
exclude: ["package.json", "src", "node_modules"]
